apiVersion: v1
kind: ConfigMap
metadata:
  name: cat-counter-pages
data:
  main.py: |
    from kubernetes import client, config
    from fastapi import FastAPI

    app = FastAPI()

    @app.get("/")
    async def root():
      config.load_incluster_config()
      v1 = client.CoreV1Api()
      ret = v1.list_namespaced_pod("default", label_selector="app=cat", watch=False)
      number_cats = len(ret.items)
      [print(i.metadata.name) for i in ret.items]
      return str(number_cats)