apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: frontend-pages
    files:
      - frontend/index.html
      - frontend/game.js
      - frontend/style.css
      - frontend/background.jpg
      - frontend/banner.png
      - frontend/closedtome.png
      - frontend/noanswers.png
      - frontend/orb.png
      - frontend/redcircle.png
      - frontend/white_noise.png

generatorOptions:
  disableNameSuffixHash: true