name: Test escape room frontend

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./init.d/02.frontend/escape-room-frontend

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x' # or specify your preferred Node.js version
          cache: 'yarn'

      - name: Upgrade Yarn
        run: npm install -g yarn

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test frontend
        run: |
          yarn && yarn ci

      - name: Test frontend docker build
        run: |
          docker build -t test .
